---
hosts: all
name: schedule clean
tasks:
- name: set default var if not defined
  set_facts:
    repo_name: '{{ repo_name | default:"beta" }}'
    repo_project: '{{ repo_project | default:"asm" }}'
  run_once: "schedule_1"

- if: repo_name == 'stable' or repo_project == 'lib'
  block:
  - name: check for not allowed variable value
    fail:
      msg: "repo_name cannot be 'stable' and repo_project cannot not be 'lib'."
    run_once: "schedule_2"
- end:

- if: pb_hostname == 'repo_server'
  block:
  - name: find specified files
    shell: >
      find {{ REPO_HOME }}/{{ repo_name }}/{{ repo_project }}/{{ repo_group }}/{{ repo_artifact }}/{{ repo_version }}
      -mtime +30 -type f
    register: find_output
- end:
