---
name: clean repo
vars_file: vars/main.yml # var_files -> vars_file, 手动引入role var

jobs:
- if: '"manual" in active'
  block:
  - job: jobs/clean/manual_clean.yml
- elif: '"schedule" in active'
  block:
  - job: jobs/clean/schedule_clean.yml
- end:

- if: repo_project != 'asm' and hostvars.repo_server.find_output.stdout_lines | length >0
  block:
  - job: jobs/clean/clean_all.yml

- elif: repo_project == 'asm' and hostvars.repo_server.find_output.stdout_lines | length >0
  block:
  - job: jobs/clean/clean_asm.yml
- end:

